name: testing

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: action/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "16.17.0"

    - name: Installing Dependecies
      run: npm i

    - name: Testing our app
      run: npm test
